#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
networks:
  hasher:
    internal: true
  redis:
    internal: true
  rng:
    internal: true
services:
  hasher:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: secobau/dockercoins:hasher-2.0
    networks:
    - hasher
  redis:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: redis
    networks:
    - redis
  rng:
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker
    image: secobau/dockercoins:rng-2.0
    networks:
    - rng
  webui:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: secobau/dockercoins:webui-2.0
    networks:
    - redis
    ports:
    - "30003:8080"
  worker:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: secobau/dockercoins:worker-2.0
    networks:
    - hasher
    - redis
    - rng
version: "3.8"
#########################################################################
